version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'Duyhn1707!'
      MYSQL_DATABASE: chamcongdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  backend:
    build: .
    image: java21-backend:latest
    container_name: java21-backend-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    # Giữ nguyên ENTRYPOINT ["java","-jar","app.jar"] từ Dockerfile,
    # và bổ sung tham số Spring Boot ở phần command để override cấu hình trong application.properties
    command:
      - "--spring.datasource.url=jdbc:mysql://db:3306/chamcongdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password=Duyhn1707!"
      - "--jwt.secret=fwsnaeojiehr3946785!@387534a8980uyw"
    restart: unless-stopped

volumes:
  mysql-data:
